export { default as Projects } from './Projects'
export { default as Documentation } from './Documentation'
export { default as Community } from './Community'
export { default as Legal } from './Legal'
export { default as TermsConditions } from './TermsConditions'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as RefundPolicy } from './RefundPolicy'
